### ISSUE TITLE
Error in the calc_AF_vectors function

### ISSUE THREAD

**Issue by PhDMattyB** [JimWhiting91/afvaper#2]
Hi there, 

I just wanted to reach out as I keep getting an error when running the calc_AF_vectors() function and I'm not sure what's causing it. The functions appears to run normally: 

Calculating AF vectors for 219 windows with 50 SNPs each
Popmap check passed, all popmap inds are in VCF
VCF check passed, all VCF inds are in popmap

then throws this error: 
Error in 1:nrow(sub_vectors) : argument of length 0

I'm trying to run afvaper on a single chromosome before scaling it up to running through multiple chromosomes. I am also using a vcf file and trying to calculate common alleles along a warm-cold ecotype gradient. My vector list  is just warm and cold individuals which matches the corresponding column in the popmap file. 

Any insight into solving this error would be amazing!

Thanks, 

Matt

**Comment by JimWhiting91** [comment]
Hi Matt,

Happy to help, could you post a snippet of the code you're trying to run so I can just check it over for anything obvious.

Cheers,
Jim

**Comment by PhDMattyB** [comment]
Definitely! I'm sure there's probably an obvious solution to it, I just couldn't figure it out. Here is the R code and I've attached a zip file with the relevant data.

Code:
chr1_vcf = read.vcfR('stickle_filtered_1.vcf')

## individual ids got duplicated in the per chr vcfs somehow
***@***.***

popmap = read_tsv('Stickleback_afvaper_popmap_dup.txt',
                  col_names = F) %>%
  as.data.frame()

vector_list <- list(c("Warm","Cold"))
names(vector_list) <- c("Cold")

# Set our window size
window_snps = 50

# Calculate Allele Frequency Change Vector Matrices
AF_input <- calc_AF_vectors(vcf = chr1_vcf,
                            window_size = window_snps,
                            popmap = popmap,
                            vectors = vector_list,
                            n_cores = 1,
                            data_type = "vcf")

All the best,


Matt

________________________________

**Comment by JimWhiting91** [comment]
Ok, so the issue here is that your vector list only includes 1 vector, warm to cold. Without knowing much about your data, this doesn't really make sense for afvaper, which is trying to calculate how parallel the trajectories of multiple vectors are in high-dimensional space. If you've only got one vector, there's nothing to compare the direction of that vector to.

It sounds like you've got 1 gradient of warm to cold and you want to identify alleles associated with that gradient, which is more akin to a GEA scan than what afvaper is doing. If however you had a bunch of populations that were cold-adapted and a bunch of populations that were warm-adapted, say pops C1-C4 and pops W1-W4, afvaper could be used to ask test whether there are parallel changes in allele frequency among the comparisons C1-W1, C2-W2, C3-W3, C4-W4. So if your data is organised like that then you could use it, but as I say without knowing more about your sampling and data it's hard to know (I can't see any zip file, sorry!).

I have considered a GEA-like usage for afvaper that would be _like_ a GEA, for instance if you could group individuals into populations and rank them on temperature, say T1 (coldest) to T5 (warmest) and test for parallel allele frequency change among the vectors T1 > T2, T2 > T3, T3 > T4, T4 > T5. This would be akin to asking whether the same haplotype consistently increases in frequency as temperature increases. I haven't however ever tested this usage, so I'd be very hesitant to recommend it!

Cheers,
Jim

**Comment by PhDMattyB** [comment]
Thanks so much for the reply! So that's on me not understanding how to structure the vector list then. I have four pairs of populations that are all diverging along a warm-cold axis and I'm interested in identifying alleles that are parallel among all populations pairs/axes. I'll restructure the vector list and give that a go. Thanks so much for the information!

All the best,


Matt Brachmann


________________________________

**Comment by JimWhiting91** [comment]
That sounds like it'll work fine then!

Assuming your pops are labelled C1-C4 and W1-W4 in your popmap, you can set up the vector list as:
```
input_vectors = list(pair1 = c("C1", "W1"),
                     pair2 = c("C2", "W2"),
                     pair3 = c("C3", "W3"),
                     pair4 = c("C4", "W4"))
```

I'll close this issue now, but if there's anything else I can help with feel free to open it up again.

Cheers,
Jim
